version: "3.8"

services:
    postgres:
        image: postgres:18
        container_name: t3-kelurahan
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: db-kelurahan
        volumes:
            - data_postgres:/var/lib/postgresql/18/docker

volumes:
    data_postgres: